name: guestbook-backend

deployments:
- containers:
    - image: tomaskral/guestbook-backend@sha256:c85c65e0a40a7645c89a31d887be66e9090df7af49d24a6a4b463f90283a2933
      envFrom:
        - secretRef:
            name: mongodb-user
        - configMapRef:
            name: mongodb-user
services:
- portMappings:
  - 3000
