# go builder image for s2i

apiVersion: v1
kind: ImageStream
metadata:
  name: go-17-centos7
spec:
  tags:
  - name: skip-download-when-vendored
    from:
      kind: DockerImage
      name: quay.io/tomkral/go-17-centos7:skip-download-when-vendored


---

kind: BuildConfig
apiVersion: v1
metadata:
  name: guestbook-backend
spec:
  strategy:
    type: Binary
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: go-17-centos7:skip-download-when-vendored 
  output:
    to:
      kind: "DockerImage"
      name: "docker.io/tomaskral/guestbook-demo-backend:latest"
    pushSecret:
      name: "pushsecrets"
  triggers:
    - type: GitHub
      github:
        secret: secret
