# go builder image for s2i

apiVersion: v1
kind: ImageStream
metadata:
  name: go-17-centos7
spec:
  tags:
  - name: skip-download-when-vendored
    from:
      kind: DockerImage
      name: quay.io/tomkral/go-17-centos7:skip-download-when-vendored


---

# output imagestream

# kind: ImageStream
# apiVersion: v1
# metadata:
#   name: guestbook-demo-backend
# spec:
#   tags:
#     - name: latest

# ---

kind: BuildConfig
apiVersion: v1
metadata:
  name: guestbook-backend
spec:
  source:
    git:
      uri: https://github.com/kadel/guestbook-demo-backend
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: go-17-centos7:skip-download-when-vendored 
  # output: 
  #   to:
  #     kind: ImageStreamTag
  #     name: guestbook-demo-backend:latest
  output:
    to:
      kind: "DockerImage"
      name: "docker.io/tomaskral/guestbook-demo-backend:latest"
    pushSecret:
      name: "pushsecrets"
  triggers:
    - type: GitHub
      github:
        secret: secret
